### ISSUE TITLE
log->notice

### ISSUE THREAD

**Issue by tpeterka** [diatomic/diy#46]
In master.hpp, line 1102: error: no member named 'notice' in 'spdlog::logger' (you will only see this in debug mode).

Use log->debug instead?

**Comment by mrzv** [comment]
It's a consequence of a change in spdlog. The levels used to be "trace, debug, info, notice, warn, error, critical, alert, emerg," but now are "trace, debug, info, warn, error, critical." I guess they simplified. We should just change this "notice" to "warn." I'll do it tomorrow (I should clean up our "no logging" functionality as well).
