### ISSUE TITLE
[pyDIY] Cannot construct DynamicAssigner class using pyDIY

### ISSUE THREAD

**Issue by jiayixu64** [diatomic/diy#80]
The constructor of DynamicAssigner requires the type of "diy::mpi::communicator" but python does not support that type. I tried three construction ways in the following but all failed. 

diy.DynamicAssigner(**master.communicator()**, size, nblocks)
diy.DynamicAssigner(**diy.mpi.MPIComm()**, size, nblocks)
diy.DynamicAssigner(**MPI.COMM_WORLD**, size, blocks)

A temporary tricky solution: 
I changed the file "bindings/python/src/assigner.cpp". I replaced the first parameter of the initializer of DynamicAssigner, "mpi::communicator comm", by "Master& m", and construct DynamicAssigner using m.communication(). Then, after recompilation, I can successfully construct DynamicAssigner by "diy.DynamicAssigner(master, size, blocks)" in python. But this way will change the API so I think there should be a better solution.

**Comment by mrzv** [comment]
Good catch. I pushed a temporary fix to `pydiy-mpi` branch in my [GitLab repo](https://gitlab.kitware.com/mrzv/diy/-/tree/pydiy-mpi). So your second line should work:

```
diy.DynamicAssigner(diy.mpi.MPIComm(), size, nblocks)
```

I want to streamline a few more things in this part of the code before merging, but you should be able to use that branch for now.

**Comment by jiayixu64** [comment]
> Good catch. I pushed a temporary fix to `pydiy-mpi` branch in my [GitLab repo](https://gitlab.kitware.com/mrzv/diy/-/tree/pydiy-mpi). So your second line should work:
> 
> ```
> diy.DynamicAssigner(diy.mpi.MPIComm(), size, nblocks)
> ```
> 
> I want to streamline a few more things in this part of the code before merging, but you should be able to use that branch for now.

Gotcha, thx!

**Comment by jiayixu64** [comment]
> Good catch. I pushed a temporary fix to `pydiy-mpi` branch in my [GitLab repo](https://gitlab.kitware.com/mrzv/diy/-/tree/pydiy-mpi). So your second line should work:
> 
> ```
> diy.DynamicAssigner(diy.mpi.MPIComm(), size, nblocks)
> ```
> 
> I want to streamline a few more things in this part of the code before merging, but you should be able to use that branch for now.

That works! I find an additional little issue: the constructor "diy.Master(.)" in the new version only accepts "MPI.COMM_WORLD" and reports an error when "diy.mpi.MPIComm()" is used.

**Comment by jiayixu64** [comment]
Also, looking forward to more APIs of DIY can be supported in pyDIY. In my project, I will transfer blocks among processes. I may need to use the APIs in "diy/include/diy/resolve.hpp" such as "fix_links" and "update_links" to dynamically update the links of blocks but it seems that pyDIY currently does not support the two APIs. I am trying to transform the two functions into python codes but find several APIs of Link classes are not available in pyDIY.

**Comment by mrzv** [comment]
What are you doing with transferring blocks between nodes? Adding proper support for this is a long-standing to-do item for DIY.

**Comment by jiayixu64** [comment]
> What are you doing with transferring blocks between nodes? Adding proper support for this is a long-standing to-do item for DIY.

Oh I see. I am doing processes' workload balance. Sometimes if a node with a high workload receives additional tasks, the node may send the tasks along with the relevant data blocks to nodes with less workload.

**Comment by mrzv** [comment]
That's precisely the use-case we are after. How generic is your code? Does it make sense to integrate into DIY itself? I have some old pre-DIY code that does this, but I'd have to re-write it more or less from scratch for DIY.

**Comment by jiayixu64** [comment]
> That's precisely the use-case we are after. How generic is your code? Does it make sense to integrate into DIY itself? I have some old pre-DIY code that does this, but I'd have to re-write it more or less from scratch for DIY.

Most of my codes for this project are based on Python and mpi4py since I need to use some machine learning libraries for some tasks. It may not be able to directly integrate them into DIY currently I think.

**Comment by mrzv** [comment]
Got you. That's Ok. I suppose if we ever get around to implementing this horizontal block movement, you'll be able to try your use-case out on it.

**Comment by jiayixu64** [comment]
> Got you. That's Ok. I suppose if we ever get around to implementing this horizontal block movement, you'll be able to try your use-case out on it.

Yup, that would be perfect if the block movement can be supported by DIY! I think for now my project just needs "update_links" of "resolve.hpp" works in pyDIY if the support of that is not complex.

**Comment by mrzv** [comment]
Are you sure you don't need `fix_links`? Either way, I added all three functions from `resolve.hpp` and pushed them on the same branch. I haven't tested it, but try it, and see if it works for you.

**Comment by jiayixu64** [comment]
> Are you sure you don't need `fix_links`? Either way, I added all three functions from `resolve.hpp` and pushed them on the same branch. I haven't tested it, but try it, and see if it works for you.

Thanks :) ! I have tested the three functions and they work well!

**Comment by mrzv** [comment]
I pushed these changes onto `master`. And I've also changed how the communicators are handled, so hopefully we run into fewer of the problems that started this issue.
