### ISSUE TITLE
Streamline contributing process

### ISSUE THREAD

**Issue by jcfr** [diatomic/diy#83]
To be consistent with [development](https://github.com/diatomic/diy#development) guidelines and streamline the contribution process, I suggest to:

* Close all pull requests and setup a GitHub action to auto close new ones adding a comment directing developer to submit merge request on gitlab. See https://github.com/marketplace/actions/close-pull-request

* Hide `Packages` section

![image](https://user-images.githubusercontent.com/219043/147168672-4d9ef066-b95e-456c-bff8-1ae5284e5384.png)

* Disable issue tracker in GitLab

* Disable `Wiki`,  `Projects` and `Discussions`, there is no need to display the extra tabs

![image](https://user-images.githubusercontent.com/219043/147167907-a031acb3-73ea-4365-bacc-4e02235862b4.png)

Cc: @mrzv

**Comment by mrzv** [comment]
I think everything is fixed, except I couldn't figure out how to hide the packages section.
