### ISSUE TITLE
Fails to build with libc++-19 because of the outdated third-party fmt.

### ISSUE THREAD

**Issue by MehdiChinoune** [diatomic/diy#92]
Reported to VTK in https://gitlab.kitware.com/vtk/vtk/-/issues/19536

**Comment by mrzv** [comment]
What version of Clang is this? The errors reported in fmt included in VTK don't seem to match what's in the actual DIY here. Is it possible VTK includes some very old version of DIY or fmt?

**Comment by MehdiChinoune** [comment]
clang-19 with libc++-19, the error won't go unless fmt version is more than 11.
Try yourself.

**Comment by mrzv** [comment]
I finally installed clang-19 and tried compiling DIY. It gave warnings unrelated to fmt, but otherwise everything compiled. Am I missing some flag? Do I need to do something special to get libc++-19?

**Comment by MehdiChinoune** [comment]
You have to install libc++-19, which distro are you using?

**Comment by mrzv** [comment]
I'm doing this in spack (under ArchLinux).

**Comment by MehdiChinoune** [comment]
I don't know about spack, but It looks like It offers libcxx https://github.com/spack/spack/blob/b0b9cf15f72c6c9c6e043ce3dbdbfd42dfe17d9a/var/spack/repos/builtin/packages/llvm/package.py#L162

You should install LLVM with libcxx and use it instead of libstdc++ by passing `-stdlib=libc++` to the compiler. In our case we use the whole LLVM toolchain as the default which is the case with FreeBSD, macOS ....

**Comment by mrzv** [comment]
I just tried that. Passed `-stdlib=libc++`. It still compiled fine. I need a way to reproduce this before I can fix it.

**Comment by MehdiChinoune** [comment]
I confirm that no issue with libc++-19 using this repo.
Sorry for the annoyance.
